services:
  easystay-front-end:
    container_name: client-container
    image: easystay-client
    restart: on-failure
    build:
      context: ./Booking-front
      dockerfile: ./Dockerfile
    ports:
      - "5293:5293"
      - "5000:5173"

  easystay-back-end:
    container_name: api-container
    image: easystay-api
    restart: on-failure
    build:
      context: ./EasyStay
      dockerfile: ./Dockerfile
    ports:
      - "5100:8080"
    volumes:
      - ./volumes/api/images:/app/Data/Images
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql-db-container
    image: postgres
    restart: on-failure
    ports:
        - "5400:5432"
    environment:
      POSTGRES_PASSWORD: devDb1234
    volumes:
        - ./volumes/db:/var/lib/postgresql/data
